config/routes.rb
App::Application.routes.draw do

  devise_for :users
  resources :posts do 
    resources :votes
    resources :comments, shallow: true
  end

  root 'posts#index'

  get '/about' =>  'pages#about'
  get '/contact' => 'pages#contact'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  has_many :votes
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :votes
  has_many :posts
  has_many :comments
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  validates :user_id, uniqueness: {scope: :post}
  # {:message => "You have already voted"} , :scope => {:post}
  belongs_to :post
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!, :except => [:index, :show, :about, :contact]
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_post
  # GET /comments
  # GET /comments.json
  def index
    @comments = @post.comments.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = @post.comments.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = @post.comments.new(comment_params)
    # @comment = current_user.comments.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @post, notice: 'Comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comment }
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    redirect_to @post
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def set_post
      if params[:post_id]
        @post = Post.find(params[:post_id])
      else
        @post = @comment.post if @comment.present?
      end
    end 

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
    params.require(:comment).permit(:title, :content, :image, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

def about
end

def contact
  
  
end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    # @unordered_posts = Post.all
    params[:sort_by] ||= 'upvote_count'

    # if params[:sort_by] != 'created_at' or params[:sort_by] != 'upvote_count'
    #   params[:sort_by] = 'upvote_count'
    # end

    @posts = 
    Post.joins("LEFT OUTER JOIN votes ON votes.post_id = posts.id").
    select('posts.*, count(votes.upvote) as upvote_count').
    where('upvote = true or upvote is null').
    group('posts.id, votes.post_id'). 
    order("#{params[:sort_by]} desc")
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find_by_id(params[:id])
    @comments = @post.comments
  end

  # GET /posts/new
  def new
    @post = current_user.posts.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = current_user.posts.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.

    def post_params
    params.require(:post).permit(:title, :content, :image)
    end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_post

  def create
    @vote = @post.votes.new(vote_params)
    @vote.user = current_user
    if @vote.save
      redirect_to :back
    else
      redirect_to :back,
      :notice => "You have already voted for this"
    end
  end

  def destroy
    @vote.destroy
  end

private

    def vote_params
    params.require(:vote).permit(:upvote, :downvote)
    end

  def set_post
    @post = Post.find(params[:post_id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
    
  # for breaking up post into paragraphs - uses redcarpet gem
  def markdown(text)
      render_options = {
    # will remove from the output HTML tags inputted by user 
    filter_html:     true,
    # will insert <br /> tags in paragraphs where are newlines 
    # (ignored by default)
    hard_wrap:       true, 
    # hash for extra link options, for example 'nofollow'
    link_attributes: { rel: 'nofollow' }
    # more
    # will remove <img> tags from output
    # no_images: true
    # will remove <a> tags from output
    # no_links: true
    # will remove <style> tags from output
    # no_styles: true
    # generate links for only safe protocols
    # safe_links_only: true
    # and more ... (prettify, with_toc_data, xhtml)
}
renderer = Redcarpet::Render::HTML.new(render_options)

extensions = {
    #will parse links without need of enclosing them
    autolink:           true,
    # blocks delimited with 3 ` or ~ will be considered as code block. 
    # No need to indent.  You can provide language name too.
    # ```ruby
    # block of code
    # ```
    fenced_code_blocks: true,
    # will ignore standard require for empty lines surrounding HTML blocks
    lax_spacing:        true,
    # will not generate emphasis inside of words, for example no_emph_no
    no_intra_emphasis:  true,
    # will parse strikethrough from ~~, for example: ~~bad~~
    strikethrough:      true,
    # will parse superscript after ^, you can wrap superscript in () 
    superscript:        true
    # will require a space after # in defining headers
    # space_after_headers: true
}
Redcarpet::Markdown.new(renderer, extensions).render(text).html_safe
end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/comments/_form.html.erb
<%= form_for([@post, @comment]) do |f| %>
  
  <%= f.label :title %>
  <%= f.text_field :title %><br>
  
  <%= f.label :content %>
  <%= f.text_area :content %><br>

  <%= f.label :image %>
  <%= f.text_field :image%><br>

  <%= f.hidden_field :user_id, :value => current_user.id %><br>

  <%= f.submit %>

<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>


    <% @comments.each do |comment| %>
     
       <%= link_to 'Show', comment %>
       <%= link_to 'Edit', edit_comment_path(comment) %>
       <%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %>
     
    <% end %>
     
   

<br>

<%= link_to 'New Comment', new_post_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', post_comments_path(@post) %>

app/views/layouts/_footer.html.erb
<footer>
    
      
      
        <div id="copyarea">
        <hr id="footsep">
        <p class="copy" id="right">Assembled in Sydney</p>
        <p class="copy">&copy;2013 Eduard Fastovski.</p>
        </div> <!--  end copyarea  -->
      
      
    </footer>

app/views/layouts/_header.html.erb
<header>


  <div id="top-band">

    <%= image_tag "GA_logo.png" %>
    <h3>A WDI Project by Eduard Fastovski</h3>
    <h1>News</h1>
    

  </div> <!-- end top band -->

  <div class="my-sticky-element">
    
    <div id="sticky-content">
      <div class="login">
        <% if user_signed_in? %>
          <p>Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></p>
        <% else %>
          <p><strong>Sign Up to Post and Vote</strong> - <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></p>
        <% end %>
      </div> <!-- end login div -->


          <div id="nav">
            <ul>
              <li><%= link_to 'Home', posts_path %></li>
              <li><%= link_to 'About', about_path %></li>
              <li><%= link_to 'Contact', contact_path %></li>
            </ul>
          </div> <!-- end nav -->

    </div> <!-- end sticky content -->

  </div> <!-- end my sticky element -->
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GA News</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>

<div class="container">

  <% if notice %>
  <p class="alert alert-notice"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-error"><%= alert %></p>
<% end %>



<%= yield %>
<div class="push"></div>

</div> <!-- end container -->
  
  <%= render 'layouts/footer' %>

<script type="text/javascript">
$(document).ready(function() {
  $('.my-sticky-element').waypoint('sticky');
});
</script>
  
</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

<p>This site was built using Ruby on Rails, on the 5th week of the Web Development Immersive at General Assembly Sydney.</p>

<p>Visit my portofolio <a href="http://edfastovski.com">edfastovski.com</a> </p>

app/views/pages/contact.html.erb
<h1>Contact</h1>


<p>Visit my portofolio <a href="http://edfastovski.com">edfastovski.com</a> </p>

<p>Email me: <a href="mailto:fedd92@gmail.com">fedd92@gmail.com</a></p>

<br>

<form action="/">
  
  <label for="name">Name:</label>
  <input type="text" name="name">
  <br>

    <label for="message">Message:</label>
<textarea name="message" id="" cols="30" rows="10"></textarea>
<br>

  <label for="email">email:</label>
  <input type="text" name="email">
  <br>

<input type="submit">

</form>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  
  <%= f.label :title %>
  <%= f.text_field :title %><br>
  
  <%= f.label :content %>
  <%= f.text_area :content %><br>

  <%= f.label :image %>
  <%= f.text_field :image%><br>

  <%= f.submit %>

<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h3 class="sort-by">Sort By <%= link_to 'Top Voted', posts_path(sort_by: 'upvote_count') %> | <%= link_to 'Newest Posts', posts_path(:sort_by => 'created_at') %> </h3>

<h2 class="new-post"><%= link_to 'New Post', new_post_path if user_signed_in? %></h2>


<div id="posts">

  <% @posts.each do |post| %>

    <div class="post <%= cycle('light', 'dark') %>">

      <div class="post-text">
        <h3><%= link_to post.title, post%></h3>
        
        <p><span class="upvotes"><%= post.votes.where(:upvote => true).count %> UpVotes </span><br> <span class="downvotes"><%= post.votes.where(:downvote => true).count %> DownVotes</span></p>

        <p>Posted by <em><%= post.user.email %></em> on <em> <%= post.created_at.to_formatted_s(:short)%> </em></p>

        <p><%= image_tag post.image, :width => '150px' %></p>
        <p><%= markdown post.content.truncate(350) %><%= link_to 'Read More', post %></p> <!-- truncate this  -->
      
      </div> <!-- end post text  -->

      <% if user_signed_in? %>

      <% vote = current_user.votes.new(:post_id => post.id) %>
        
        <div class="upvote-button">
        <%= form_for([post, vote]) do |f| %>
          <%= f.hidden_field :upvote, :value => true %>
          <%= f.submit 'Vote Up' %>
        <% end %>
        </div>

        <div class="downvote-button">
        <%= form_for([post, vote]) do |f| %>
          <%= f.hidden_field :downvote, :value => true %>
          <%= f.submit 'Vote Down' %>
        <% end %>
        </div>


        <%= link_to 'Edit', edit_post_path(post) if user_signed_in? && current_user == post.user %>
        <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } if user_signed_in? && current_user == post.user %>

      <% end %>

    </div><!-- end post div -->

  <% end %>

</div> <!-- end posts div -->

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="post-text">
  <h2><%= @post.title %></h2>
  <p><span class="upvotes"><%= @post.votes.where(:upvote => true).count %> UpVotes </span><br> <span class="downvotes"><%= @post.votes.where(:downvote => true).count %> DownVotes</span></p>
  <p>Posted by <em><%= @post.user.email %></em> on <em><%= @post.created_at.to_formatted_s(:short)%></em> </p>
  <%= image_tag @post.image, :width => '400' %>
  <p><%= markdown @post.content%></p>
</div> <!-- end post-text -->

<% if user_signed_in? %>

  <% vote = current_user.votes.new(:post_id => @post.id) %>

  <div class="upvote-button">
  <%= form_for([@post, vote]) do |f| %>
    <%= f.hidden_field :upvote, :value => true %>
    <%= f.submit 'Vote Up' %>
  <% end %>
  </div>

  <div class="downvote-button">
  <%= form_for([@post, vote]) do |f| %>
    <%= f.hidden_field :downvote, :value => true %>
    <%= f.submit 'Vote Down' %>
  <% end %>
  </div>

<% end %>


<%= link_to 'Comment', new_post_comment_path(@post) %> 
<%= link_to 'Edit', edit_post_path(@post) if user_signed_in? && current_user == @post.user %> 
<%= link_to 'Back', posts_path %>


<div class="comments">

  <% @comments.each do |comment| %>

  <div class="comment">
  
    <h4><%= comment.title%></h4>
    <p><%= comment.content%></p> <!-- truncate this  -->
    <p>Posted by <em><%= comment.user.email %></em> on <em><%= comment.created_at.to_formatted_s(:short)%></em></p>

    <%= link_to 'Delete Comment', comment_path(comment.id), :method => :delete %>

  </div> <!-- end individual comment div -->

  <% end %>
</div> <!-- end comments area -->